# Nombre de la aplicacion
spring.application.name=reservas-labs-api

# H2 base de datos embebida
spring.datasource.url=jdbc:h2:mem:reservas_labs_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto del servidor
server.port=8080

# Generación automática de tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true